// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"AddAutoToActorCommand","status":true,"description":"Add 'Auto' command on the top or bottom of Actor Command","parameters":{"commandName":"Auto Select","autoCommandPos":"0"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}},
{"name":"Levelupstate","status":true,"description":"Gives you a state when you level up","parameters":{"leupid":"11"}},
{"name":"AltMenuScreen2MZ","status":false,"description":"[Ver1.1.2]Yet another menu screen layout","parameters":{"allowWindowDisp":"true","maxColsMenu":"4","commandRows":"2","commandCols":"4","isDisplayStatus":"true","display map name":"true","location string":"Location:","bgBitmapMenu":"","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":"","doesNotSetShopScene":"false","bgBitmapShop":"","doesNotSetNameScene":"true","bgBitmapNameInput":"","bgUserDefined":""}},
{"name":"ChangeEquipOnBattleMZ","status":true,"description":"[Ver1.1.0]Add equipment change command to actor commands","parameters":{"commandName":"Equip"}},
{"name":"ItemCombineScene","status":true,"description":"Make new menu scene that combine items to make reinforced item","parameters":{"isDebugMode":"false","commandName":"Reinforce Item","playType":"ME","seName":"Chime2","meName":"Item","dummy4text":"","textBefore":"Before:","textAfter":"After:","textCombineYes":"Yes","textCombineNo":"No","textSelectMaterial":"Select the material.","textSelectFromCandidate":"Select the item to reinforce.","textSureToCombineEquipped":"Are you sure to combine %1's equip?","textSureToCombineNormal":"Are you sure to combine them?"}},
{"name":"ItemNameMsg","status":true,"description":"at message window, \\ITEM[] replace to item name.","parameters":{}},
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Show FPS Counter":"false","Fullscreen":"false","Simulate Production Env":"false"}},
{"name":"CGMZ_Professions","status":true,"description":"Creates a profession system for your game","parameters":{"Professions":"[]","Window Options":"","Transparent Windows":"false","Background Image":"","Total Level Text":"Total Level:","ScrollSpeed":"1","ScrollWait":"300","Scroll Deceleration":"0.92","Auto Scroll":"true","Text Options":"","Label Color":"16","Description Alignment":"left","Level Text":"Level:","Exp Text":"Experience:","Exp To Level Text":"Experience To Level:","Description Text":"Description:","Other CGMZ Plugin Options":"","Show Level Up Toast":"true","Level Up Text":"has leveled up!","Show Discover Toast":"true","Discover Text":"Discovered Profession"}},
{"name":"CGMZ_TitleCommandWindow","status":true,"description":"Manage the menu command window","parameters":{"Visible Commands":"3","Alignment":"center","Keep Original Commands":"true","Enable Text Codes":"true","Commands":"[]"}}
];
